### ISSUE TITLE
Missing all IGH fusions

### ISSUE THREAD

**Issue by ndaniel** [Oshlack/JAFFA#32]
Hello,

I run JAFFA v1.0.8 on [this RNA-seq dataset](https://sourceforge.net/projects/fusioncatcher/files/test/), which contains 17 known fusion genes:

- FGFR3-TACC3
- FIP1L1-PDGFRA
- GOPC-ROS1
- EWS-ATF1
- TMPRSS2-ETV1
- EWS-FLI1
- NTRK3-ETV6
- CD74-ROS1
- HOOK3-RET
- EML4-ALK
- AKAP9-BRAF
- BRD4-NUT
- MALT1-IGH
- IGH-CRLF2
- DUX4-IGH
- NPM1-ALK
- CIC-DUX4

where the reads supporting these fusions were selected manually.

When running JAFFA (in hybrid mode), it looks like JAFFA is finding only 10 fusions, which are:
- GOPC:ROS1
- EWSR1:ATF1
- AKAP9:BRAF
- ETV6:NTRK3
- HOOK3:RET
- EWSR1:FLI1
- BRD4:NUTM1
- CD74:ROS1
- FGFR3:TACC3
- TMPRSS2:ETV1

and JAFFA is missing the following 7 fusions:
- FIP1L1-PDGFRA
- GOPC-ROS1
- MALT1-IGH
- IGH-CRLF2
- DUX4-IGH
- NPM1-ALK
- CIC-DUX4

See [here](https://github.com/Oshlack/JAFFA/files/912318/jaffa_results.zip) for JAFFA's results.

Are these results correct? Please, could you concur this?

Is JAFFA able to find IGH fusion genes?

Best Regards,
Daniel

**Comment by nadiadavidson** [comment]
Hi Daniel,

I've heard from another that an IGH fusion was missed by JAFFA, so it's possible it's not sensitive to them. This is something we would like to fix in future of course because they are clinically important (please leave this issue open in github as a reminder to us). 

As for the other missed fusions, there could be a variety of reasons for that. For example JAFFA can not detect fusions if any intronic sequence has been retained. I tested the direct mode of JAFFA on your test data and get similar results, so I don't think there's a technical problem with your run. Although I did have to manually modify some of the code because some of the quality scores appear to be strange. Does the test data have a mixture of 33 and 64 offset quality scores? 

Cheers,
Nadia.

**Comment by ndaniel** [comment]
Hi Nadia,

there are fusion finders which are able to find IGH fusions just fine in RNA-seq data. I think that most of the cases IGH fusions are missed due to a combination of reasons (e.g. IGH annotations in GTF file, some IGH fusions have random inserts at fusion junctions, etc.)

I do not know why JAFFA is missing the other non-IGH fusions but I guess that probably is a different reason for each fusion.

Regarding the mixture 33 an 64 quality scores I have noticed it too. I need to look into that. When running JAFFA I used this Python script (called `fix.py`), as workaround, to convert the FASTQ files in a format accepted by JAFFA (by converting all quality values to `IIIIIIIIIII`):
```
#!/usr/bin/env python
"""
Run as.

fix.py reads_1.fq reads_1.fastq
"""


import os
import sys


i = sys.argv[1]
o = sys.argv[2]

fi = open(i,"r")
fo = open(o,"w")
z = 10**6
j = -1
while True:
    lines = fi.readlines(z)
    if not lines:
        break
    n = len(lines)
    for k in xrange(n):
        j = j + 1
        if j == 3:
            lines[k] = (len(lines[k]) -1 ) * 'I' +'\n'
            j = -1
    fo.writelines(lines)
fi.close()
fo.close()
```

**Comment by ndaniel** [comment]
I checked and indeed there was a bug affecting qualities for some reads. I have fixed that by converting all qualities to Sanger, and now the [test RNA-seq FASTQ files](https://sourceforge.net/projects/fusioncatcher/files/test/) should be fine. On these JAFFA gives the same results as before.
