### ISSUE TITLE
trying to understand overall workflow of JAFFA

### ISSUE THREAD

**Issue by serine** [Oshlack/JAFFA#46]
Hi there, 

I'd like to understand better what happens under the hood so to speak of JAFFA. Reading the `JAFFA_stage.groovy` this is my understanding so far

- trim raw fastq files with `trimmomatic` (this is I/O blocking by the way)
- map trimmed fastqs with `bowtie2`, stage 1, against transcriptome, discard the bam (alignment file) and only keep unaligned reads
- map unmapped reads from stage 1 with `bowtie2`, stage 2, against masked genes (which genes are these?)
-  map unmapped reads from stage 2 with `bowtie2`, stage 3, against transcriptome (again?) and only take reads that are mapped?
- map mapped reads from stage 3 with `blat` against transcriptome (why?) 
- the rest are few steps to do with extracting, narrowing down candidates and preparing results table, all done in `R`

I also have a few technical questions.

> Q1
 
`mapParams` variable is set to:

```
mapParams="-k1 \              // report single alignment per read
           --no-mixed \       // suppress unpaired alignments for paired reads
           --no-discordant \  // suppress discordant alignments for paired reads
           --mm"              // use memory-mapped I/O for index; many bowties can share

``` 

I'm specifically concerned about `--no-discordant` flag. From reading [bowties2 docs](http://bowtie-bio.sourceforge.net/bowtie2/manual.shtml) it appears to me that `--no-discordant` means you are not allowing discordant reads. I thought most gene fusion events would result from discordant reads ? Am I miss understanding this?

> Q2

After stage 1 and 2 of `bowtie2` mapping you go on to do this 

```
$bowtie2 -k1 \
         -p $threads \
         --un ${output.dir}/unmapped.fastq \
         -x $transFasta.prefix \
         -U $input_string | \
$samtools view -s 1.0 \                         // setting random seed, not sure why?
               -F 4 \                           // bitflag 4 == unmapped reads, -F all the reads that dont have the bitflag, there get all reads that mapped
               -S -b - | \
$samtools sort - $output2.prefix ;
$samtools index $output2 ;
```

and you call this stage `get_unmapped` reads, but you are taking reads that haven't mapped to the transcriptome and to masked genes and mapping it again against transcriptome, grabbing the reads that mapped `-F 4`. Am I correct here? This is a bit confusing to me, what is this step doing exactly? 

I was following along with mapping to transcriptome with the idea that chimeric reads wouldn't map to "normal" transcriptome and thereby harvesting unmapped reads as putative gene fusion reads. I also understand that you masking genes could be some known genes/regions that typically result in chimeric reads, but known to be not interesting.  But then I got lost with stage 3 `bowtie2` mapping

> Q3 

About `blat`, does it give high sensitivity for chimeric alignment? Also would you not want to map against genome rather then transcriptome with `blat`? 
Do you think it would be sensible to use splice aware aligner e.g STAR instead of `blat` and map against genome? In theory all alignment should be chimeric once right?  (I'm not suggesting to adopt STAR into JAFFA, just talking about the workflow)

Many thanks in advance.

p.s I wasn't sure if this discussion was better suited for your google group forum, but it doesn't have markdown support

**Comment by nadiadavidson** [comment]
Hi, to answer your questions:
1. --no-discordant is used precisely for the reason you give. We keep the unmapped reads, so it's a bit like a double negative. If you take the scenario where one reads maps perfectly to a gene and the other doesn't because it spans the fusions break, we want to capture both reads in the "unmapped" output.
2. This extra alignment is used to separate the spanning reads and spanning pairs. ie. reads which contain the break should go into unmapped.fastq and reads where each end aligns to a different gene go into *_discordant_pairs.bam. The reads from unmapped.fastq then go on to be checked for candidates and later on the results are checked against the discordant pairs file to add information about spanning pair support.
3. Yes, the idea here is that blatting to the transcriptome is very sensitive. There are possibly faster choices than blat these days, but this was a good open when we wrote JAFFA. We intentionally stayed away from aligning to the genome or using a splice aware aligner, because allowing introns/splicing in the alignment can increase the rate of false positives. Aligning to a transcriptome removes that complexity and makes a lot of sense intuitively because the transcriptome is what we sequence. It's also a lot smaller. It's for this reason that I guess tools like kallisto and salmon have also adopted a transcriptome reference approach in the last few years (although obviously they address a different problem than fusion finders). Another reason for this decision was that we wanted JAFFA to work with long sequences (either from de novo assembly or long read sequencing). Blat works really well in this case and the splice aware aligners did not work as well. They were really optimised for short read sequencing and illumina error rates (although this may have changed since JAFFA was published).

I'm happy to answer any other questions you have!

Cheers,
Nadia.

**Comment by serine** [comment]
This is great, thanks so much for clarification

**Comment by ahwanpandey** [comment]
> Hi, to answer your questions:
> 
> 1. --no-discordant is used precisely for the reason you give. We keep the unmapped reads, so it's a bit like a double negative. If you take the scenario where one reads maps perfectly to a gene and the other doesn't because it spans the fusions break, we want to capture both reads in the "unmapped" output.
> 2. This extra alignment is used to separate the spanning reads and spanning pairs. ie. reads which contain the break should go into unmapped.fastq and reads where each end aligns to a different gene go into *_discordant_pairs.bam. The reads from unmapped.fastq then go on to be checked for candidates and later on the results are checked against the discordant pairs file to add information about spanning pair support.
> 3. Yes, the idea here is that blatting to the transcriptome is very sensitive. There are possibly faster choices than blat these days, but this was a good open when we wrote JAFFA. We intentionally stayed away from aligning to the genome or using a splice aware aligner, because allowing introns/splicing in the alignment can increase the rate of false positives. Aligning to a transcriptome removes that complexity and makes a lot of sense intuitively because the transcriptome is what we sequence. It's also a lot smaller. It's for this reason that I guess tools like kallisto and salmon have also adopted a transcriptome reference approach in the last few years (although obviously they address a different problem than fusion finders). Another reason for this decision was that we wanted JAFFA to work with long sequences (either from de novo assembly or long read sequencing). Blat works really well in this case and the splice aware aligners did not work as well. They were really optimised for short read sequencing and illumina error rates (although this may have changed since JAFFA was published).
> 
> I'm happy to answer any other questions you have!
> 
> Cheers,
> Nadia.

Hi Nadia,

Seems like there is a multithreaded version of blat that might speed up JAFFA. Maybe it could be worthwhile implementing this in a future update for both v1 and v2 JAFFAs?

https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-019-2597-8

Thanks!

**Comment by nadiadavidson** [comment]
Hi,

Thanks for the suggestion. I have a feeling I tried to switch to pblat, but it kept crashing at the time. 
JAFFA underwent a large rewrite with version 2 and one change was switching the transcriptome alignment step to blast, which turned out to be faster than blat and is also mult-threaded! I also tested gmap and some others, but blast turned out to be the best! I guess because we aren't doing spliced alignment when we align RNA-Seq to a reference transcriptome. The genome alignment is still performed with blat, but this was not that time consuming since only a subset of reads are aligned.
As a result of all the changes JAFFA version 2 runs much faster than version 1.

Cheers,
Nadia.

**Comment by ahwanpandey** [comment]
Thanks for the reply!

I do want to use JAFFA 2 but it doesn't support hg19 right?

Also, downloading references for hg38 was taking forever from the website you've uploaded to, my ETA was 3 days!

**Comment by nadiadavidson** [comment]
Yes, that's right, but building a hg19 reference for JAFFA 2 is something we should probably do.
I'll open a new issue to remind myself about this and investigate if we can make the file smaller (or provide a script to generate it locally). Thanks!

**Comment by ahwanpandey** [comment]
Thanks so much! One last question, is the main difference between JAFFA 1 and 2 if I run it on the usual 100bp paired end illumina RNAseq just the speed or would JAFFA 2 give "better" results?

**Comment by nadiadavidson** [comment]
That's a really important question. The short answer is it's about the same as version 1 in accuracy. But it will not give exactly the same results. ie. some fusions which were detected with version 1 will be miss and some others which were missed will be found. So if you are running on clinical samples, it could be worth doing some independent benchmarking to check (fortunately it runs faster, so rerunning over a cohort is doable).

In our benchmarking of Direct mode (simulation + cell line + patient cohorts) version 2 was a little more sensitive, but also reported a few more false positives.

**Comment by ahwanpandey** [comment]
Thanks for your detailed responses and suggestions! 

Might I add about the references, other than the things you've already mentioned, one other option to think of maybe would be to host it on a faster server? I think the one that is hosting it currently is just very slow.

Thanks again for your time!

**Comment by nadiadavidson** [comment]
Thanks for this suggestion, I'll look into it.
