### ISSUE TITLE
jaffal error

### ISSUE THREAD

**Issue by readmanchiu** [Oshlack/JAFFA#61]
Hi,

I was trying to do run jaffal and stopped by the following error:
```
cat SRR12010483.sra.fastq/SRR12010483.sra.fastq.txt | awk '{print $1}' > SRR12010483.sra.fastq/SRR12010483.sra.fastq.fusions.fa.temp ;                 /projects/xxx/yyy/jaffa/JAFFA-version-2.1/tools/bin/reformat in=SRR12010483.sra.fastq/SRR12010483.sra.fastq.fasta out=stdout.fasta fastawrap=0 |  SRR12010483.sra.fastq/SRR12010483.sra.fastq.fusions.fa.temp > SRR12010483.sra.fastq/SRR12010483.sra.fastq.fusions.fa ;                 rm SRR12010483.sra.fastq/SRR12010483.sra.fastq.fusions.fa.temp ;
```
should there be some executable after the pipe in the command???
```
|  SRR12010483.sra.fastq/SRR12010483.sra.fastq.fusions.fa.temp > SRR12010483.sra.fastq/SRR12010483.sra.fastq.fusions.fa
```
Output after running `bpipe errors`:
```
============================= Found 1 failed commands from run 159543 ==============================

============================================ Command 9 =============================================

Command    : cat SRR12010483.sra.fastq/SRR12010483.sra.fastq.txt | awk '{print $1}' > SRR12010483.sra.fastq/SRR12010483.sra.fastq.fusions.fa.temp ;                 /projects/xxx/yyy/jaffa/JAFFA-version-2.1/tools/bin/reformat in=SRR12010483.sra.fastq/SRR12010483.sra.fastq.fasta out=stdout.fasta fastawrap=0 |  SRR12010483.sra.fastq/SRR12010483.sra.fastq.fusions.fa.temp > SRR12010483.sra.fastq/SRR12010483.sra.fastq.fusions.fa ;                 rm SRR12010483.sra.fastq/SRR12010483.sra.fastq.fusions.fa.temp ;
Exit Code  : 1
Output     : 

No command output found in most recent log file
```

**Comment by nadiadavidson** [comment]
Yes, you are right, there should be a "extract_seq_from_fasta" after the pipe. This likely means that it was not installed. You can check in tools.groovy in the directory where you installed JAFFA and it's likely the path to this program will be empty. When you ran ./install_linux64.sh, if should have compiled it or thrown an error. You can try rerunning this script and send me the output to see what's gone wrong. Otherwise you can compile/install manually: from the directory when you ran install_linux64.sh, "cd tools" then "g++ -O3 -o bin/extract_seq_from_fasta ../src/extract_seq_from_fasta.c++", and let me know what it does.

Cheers,
Nadia.

**Comment by nadiadavidson** [comment]
This flag has now been added to the master code branch.
