### ISSUE TITLE
Trying to understand JAFFAL ONT intermediate file XXX_merged.fq.txt

### ISSUE THREAD

**Issue by MikaQiao** [Oshlack/JAFFA#71]
Hi there,

I am using JAFFAL to call fusions from ONT data, and I've found the supported reads file that I am interested in, named `XXX_merged.fq.txt`. But I am confused about the intepretation of this file. can you give me some help?

Blew are the first few lines of the file:
![image](https://user-images.githubusercontent.com/29300358/153541395-83a7b970-c014-4c7d-be2a-d9d36c27c364.png)

Best,
Mika

**Comment by nadiadavidson** [comment]
Hi Mika,

The columns in this file are:
1. The ID of the read
2.and 3. Approximate upper and lower range of breakpoint base *in the read*
4. The fusion name (two gene involved)
5. Length of the read
6. The reference transcript ID matching the first half of the fusion transcripts
7. End base of the alignment between read and 1st reference transcript *in the reference transcript*
8. The reference transcript ID matching the second half of the fusion transcripts
9. Start base of the alignment between read and 2nd reference transcript *in the reference transcript*
10. and 11. These are also related to breakpoint (alignment end/start) positions *in the read*
12. The strand of the read relative to the reference transcript. ie. '+' they run in the same direction, otherwise '-' means the read will be the reverse compliment.

If you want to get the matching read sequences you can use a bash command like:
grep "PML:RARA" XXX_merged.fq.txt | cut -f1 | grep -f - -A1 XXX_merged.fq.fusions.fa 
This will extract all the read IDs for the fusion "PML:RARA" and then search for them in the intermediate file ending in fusions.fa.

There might be a few errors in the line above as I'm writing it from memory, but hopefully it's helpful.
Please let us me know if you have any other questions.

Cheers,
Nadia.

**Comment by MikaQiao** [comment]
Hi Nadia, 

This is really helpful, thank you so much!

**Comment by evanwangx** [comment]
Hi Nadia,

I've also looking at supporting reads of the final fusion calls from Nanopore input. 

When I grep the fusion I'm interested in from this intermediate .TXT file, there are hundreds of reads that pop up (and shown in IGV when I load the PSL file), but when I look at the final summary file it shows only a handful of supporting reads in the Spanning Reads column. Just wondering about the reason for this discrepancy.

Thanks!

**Comment by nadiadavidson** [comment]
Hi,

The reads are failing some of the later filters for some reason. This would usually only happen for a few % up to about 30% of fusions reads from the data I've looked at. My hunch is that your fusion might include a few extra bases of intronic or other inserted sequence which JAFFAL usually doesn't handle. The aligned reads in IGV might give you an indication if something like this is the issue. I'm happy to investigate further if you'd like to send some example reads or IGV screen shoots.

Cheers,
Nadia.

**Comment by evanwangx** [comment]
Hi, could I send the data by email? Thanks!

**Comment by nadiadavidson** [comment]
Certainly! email address is nadiamdavidson@gmail.com

**Comment by nadiadavidson** [comment]
Will close this issue now, but feel free to correspond through email.

**Comment by evanwangx** [comment]
Hi, could I send the data by email? Thanks!
