### ISSUE TITLE
arm64 mac

### ISSUE THREAD

**Issue by itslittman** [Oshlack/JAFFA#89]
Can I run this on mac os?

Noah

**Comment by nadiadavidson** [comment]
Hi Noah,

In theory you can, but you'd need to install all the dependent software. So for example, you could modify the install_linux.sh file for mac binaries where available and/or change the tools.groovy file to point to all the required software. You would definitely need to have a c compiler installed on your mac.

However, for anything but very small fastq file, I'd advise using a server or HPC because of the computational resources required. Best of luck.

Cheers,
Nadia.

**Comment by itslittman** [comment]
@nadiadavidson okay thanks! How big do you consider a 1gb-3gb fastq file to be?

noah

**Comment by nadiadavidson** [comment]
Hi @itslittman, although not the largest, they would take quite a while to process I think.

Best of luck!
