### ISSUE TITLE
Custom references for JAFFAL !!!

### ISSUE THREAD

**Issue by KMBelal** [Oshlack/JAFFA#98]
Hi all,

I've analyzed the simulated demo data using JAFFAL and the program successfully detected the fusion transcript. 

Now I want to use JAFFAL to analyze Nanopore data to identify virus-host chimeric transcript. But the issue is the references. I have the .gtf format of the custom reference where the virus sequence was added as a separate chromosome. 
Is it okay to use this as a reference??
If okay, maybe to run JAFFAL, I need the .tab, .fasta and .BED format of the custom reference, can you help me if I could convert .gtf to .tab/.fasta/.BED format.

Thanking you,
Belal

**Comment by nadiadavidson** [comment]
Hi Belal,

Apologies for not seeing this post earlier. You have probably already moved on, but I'll answer in case others are interested. To make a custom reference, you need to generate the .tab, .fasta and .bed formats. For the .bed and .fasta there are a number of tools which can do this if you have a .gtf and genome reference already. The .tab is a little more complicated as it's not a standard format, but a table generated by UCSC genome browser. So for many organisms, it won't be available, and you would need to write a script to covert yourself. There is some information available about generating custom references (for organisms that are in UCSC), in case you haven't seen that already: https://github.com/Oshlack/JAFFA/wiki/FAQandTroubleshooting#how-can-i-generate-the-reference-files-for-a-non-supported-genome

Looking for viral chimera's is an interesting application, and we could also thinking about having some common viruses (e.g HPV) packaged with the release reference if it would be useful to the community.

Cheers,
Nadia.

**Comment by mpizzagalli777** [comment]
Hi Nadia, 
I had a follow up question regarding this issue. I would like to identify fusions that involve transposable elements in the human genome. How would I go about including these sequences in the reference information for JAFFAL? Looking at the information provided at the link above, I can generate the required files but I assume I need to include information for the transposable elements in these files as well. Do you have any suggestions on how I can do that? I also noticed that the .tab file that is provided with JAFFA has different column names that the ones that come when I download the newer annotation. Finally, would I have to rename the TEs with "EN" at the start (since JAFFA expects that prefix)?
